@startuml Complete diagram

namespace eMSP_APP <<frame>>{
   	interface OSInterface{
    	+ requestHandler(request)
		+ start(Activity)
		+ notify(msg)
   	}
   
   	interface MainInterface{
		+ chargeButtonPressed()
		+ chargingStationSelected(CS)
		+ bookForChargeButtonPressed()
		- isLogged()
		- updatePosition(search_string)
		- locateUser()
		- insertMapMarkers(CS)
	}	

	interface ChargingInterface{
		+ committToken()
		- parseToken()
		- prepareBill()
	}

	interface SigningInterface{
		+ loginButtonPressed()
		+ loginForm(user,psw)
		+ registerButtonPressed()
		+ registerForm(data)
		- validateInput(data)
	}

	interface ReservationInterface{
		+ reservationForm(reservation)
		- validateInput(data)
	}

	interface NotificationInterface{
		+ serviceStartup()
	}

	OSInterface<|..|>MainInterface
	OSInterface<|..|>ChargingInterface
	OSInterface<|..|>SigningInterface
	OSInterface<|..|>ReservationInterface
	OSInterface<|..NotificationInterface	
}




namespace eMSP_Server <<frame>>{
   	interface eMSP_API{
		+ requestHandler(request)
   	}
   
   	interface RegistrationInterface{
		+ login(user, psw)
		+ register(data)
		+ verifyMail(mail)
	}	

	interface NotificationInterface{
		+ missedRservation(user)
		+ chargeCompleted(user)
		+ getNotifications(user)
	}

	

	eMSP_API..|>RegistrationInterface
	eMSP_API..|>NotificationInterface
}



namespace CPMS_Server <<frame>>{
   	interface CPMS_API{
		+ requestSender(request)
		+ requestHandler(request)
   	}

	interface GraphicsInterface{
		+ changeDSOSelected()
		+ showDSOList()
		+ filterDSOs(filter)
		+ changeDSO(form)
		+ loginForm(user,psw)

	}
   
   	interface PowerManagerInterface{
		+ getDSOs()
		+ filterDSOs(filter)
		+ requestDSOChange(DSO)
		+ selectBestDSO()		
		- applyFilter(list, filter)

	}	

	interface ReservationInterface{
		+ requestReservation(reservation)
	}

	interface InfoInterface{
		+ getInfo()

	}

	interface AuthorizationInterface{
		+ login(user,psw)
		- verifyInput(user,psw)
	}

	

	interface ChargingInterface{
		+ checkReservation(token)
	}

	
	CPMS_API..|>ReservationInterface
	CPMS_API..|>InfoInterface
	CPMS_API..|>AuthorizationInterface
	CPMS_API..|>ChargingInterface
	CPMS_API..|>GraphicsInterface

	GraphicsInterface..|>PowerManagerInterface





}

package Users_DBMS <<Database>>{
		interface Users_DBMS_API{
			+ find(name,psw)
			+ insert(User)
			+ update(User)
		}
	}


package Reservations_DBMS <<Database>>{
	interface Reservations_DBMS_API{
		+ find(reservation)
		+ insert(reservation)
		+ remove(reservation)
	}
}

interface CPOs_API{
	+ getCPMSs() 
	+ verifyUserCredentials(user, psw)
}

interface DSOs_API{
	+ getDSOs()
	+ stipulateContract(DSO)
}

interface Payment_API{
	+ pay(info,bill)
	+ verifyPaymentMethod()
}

interface ChargingColumn_API{
	+ getFreeSockets()
	+ getChargingStatus(socket)
	+ isSocketUnplugged(socket)
}

interface BatteryPack_API{
	+ getLevel()
	+ getEnergyValue()
	+ fillBattery()
}	

interface Switcher_API{
	+ startBatterySupply()
	+ startDSOSupply()
}


eMSP_APP.OSInterface..|>eMSP_Server.eMSP_API
eMSP_APP.OSInterface..|>CPMS_Server.CPMS_API
eMSP_APP.OSInterface..|>CPOs_API
eMSP_APP.OSInterface..|>Payment_API


eMSP_Server.RegistrationInterface..|>Users_DBMS_API

CPMS_Server.CPMS_API..|>eMSP_Server.eMSP_API

CPMS_Server.InfoInterface..|>Reservations_DBMS_API

CPMS_Server.PowerManagerInterface..|>ChargingColumn_API
CPMS_Server.PowerManagerInterface..|>BatteryPack_API
CPMS_Server.PowerManagerInterface..|>Switcher_API
CPMS_Server.PowerManagerInterface..|>DSOs_API

CPMS_Server.ChargingInterface..|>ChargingColumn_API
CPMS_Server.ChargingInterface..|>Switcher_API
CPMS_Server.ChargingInterface..|>Reservations_DBMS_API

CPMS_Server.ReservationInterface..|>Reservations_DBMS_API





@enduml

